{% set name = "dabl" %}
{% set version = "0.2.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 104dad3eb4fed61b7be4310670c79537ed3a51289c1abcee298891705029aa83

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - matplotlib-base >=3.8
    - numpy
    - pandas
    - scikit-learn >=1.1
    - scipy
    - seaborn

test:
  imports:
    - dabl

about:
  home: https://github.com/dabl/dabl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: This project tries to help make supervised machine learning more accessible for beginners, and reduce boiler plate for common task
  doc_url: https://dabl.github.io/dev/
  dev_url: https://github.com/dabl/dabl

extra:
  recipe-maintainers:
    - krisevans
    - dhirschfeld
